### ISSUE TITLE
Tethering with Rinkeby is not working

### ISSUE THREAD

**Issue by horca17** [kaleido-io/kaleido-main-net#1]
Using getenv.js to bridge with Rinkeby and obtain some data/confirmation using deployed Kaleido contract 0x35afbaaa24ffb0b360a8c14734bd9a583b092154 has not been working for 45 days, so one of the main advantages of using Kaleido is not addressed jet, can you provide some update?

<img width="1205" alt="screen shot 2018-07-25 at 12 37 03 am" src="https://user-images.githubusercontent.com/5912700/43178268-eb867dc6-8fa2-11e8-9bfa-d2dd01e8f027.png">

thanks.

**Comment by azeem-r00t** [comment]
Hi Horacio, 

Thanks for bringing this to our attention. We are currently debugging this issue. It seems restricted to certain environments and I hope to have another update for you later today.

Thanks,
Azeem

**Comment by azeem-r00t** [comment]
Hi Horacio, 

These issues have been resolved. We expect to have the fix in production in all geos in a day or two after it has gone through the tests. 

Thanks,
Azeem
